<a href="https://colab.research.google.com/github/lyonnce/100days/blob/master/Interaction0306.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression
#2020.03.06 Friday CLass
#找出两个变量对y的一起带来的influence synergy effect 



In [0]:
adv = pd.read_csv('/content/drive/My Drive/DS_Feb_21/data/advertising.csv')

In [0]:
adv.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [0]:
adv['rtv'] = adv['radio']*adv['TV']
adv.head()

Unnamed: 0     TV  radio  newspaper  sales      rtv
0           1  230.1   37.8       69.2   22.1  8697.78
1           2   44.5   39.3       45.1   10.4  1748.85
2           3   17.2   45.9       69.3    9.3   789.48
3           4  151.5   41.3       58.5   18.5  6256.95
4           5  180.8   10.8       58.4   12.9  1952.64

In [0]:
X = np.array(adv[['TV','radio','rtv']])
y = np.array(adv['sales'])
model3 = LinearRegression().fit(X=X,y=y)
model3.score(X,y)

0.9677905498482523

In [0]:
model3.coef_

array([0.01910107, 0.02886034, 0.00108649])

In [0]:
#use polynomial features 来一个个试每个variable之间的synergy
#interaction_only = True 只看不同variable 之间的interaction i.e. ac,ab, bc, not aa,cc,bb


In [0]:
from sklearn import preprocessing 
import statsmodels
from sklearn.preprocessing import PolynomialFeatures
le = preprocessing.LabelEncoder()

In [0]:
X = np.array(adv[['TV','radio','newspaper']])
y = np.array(adv['sales'])
model3 = LinearRegression().fit(X=X,y=y)
model3.score(X,y)

0.8972106381789521

In [0]:
#X= np.arange(6).reshape(3,2)
interaction = PolynomialFeatures(degree = 2, include_bias = False, interaction_only = False)
X_inter = interaction.fit_transform(X) #先define变形的样子
X_inter


array([[ 230.1 ,   37.8 ,   69.2 , ..., 1428.84, 2615.76, 4788.64],
       [  44.5 ,   39.3 ,   45.1 , ..., 1544.49, 1772.43, 2034.01],
       [  17.2 ,   45.9 ,   69.3 , ..., 2106.81, 3180.87, 4802.49],
       ...,
       [ 177.  ,    9.3 ,    6.4 , ...,   86.49,   59.52,   40.96],
       [ 283.6 ,   42.  ,   66.2 , ..., 1764.  , 2780.4 , 4382.44],
       [ 232.1 ,    8.6 ,    8.7 , ...,   73.96,   74.82,   75.69]])

In [0]:
interaction = PolynomialFeatures(degree = 2, include_bias = False, interaction_only = True)
X_inter = interaction.fit_transform(X) #先define变形的样子
X_inter

array([[2.301000e+02, 3.780000e+01, 6.920000e+01, 8.697780e+03,
        1.592292e+04, 2.615760e+03],
       [4.450000e+01, 3.930000e+01, 4.510000e+01, 1.748850e+03,
        2.006950e+03, 1.772430e+03],
       [1.720000e+01, 4.590000e+01, 6.930000e+01, 7.894800e+02,
        1.191960e+03, 3.180870e+03],
       ...,
       [1.770000e+02, 9.300000e+00, 6.400000e+00, 1.646100e+03,
        1.132800e+03, 5.952000e+01],
       [2.836000e+02, 4.200000e+01, 6.620000e+01, 1.191120e+04,
        1.877432e+04, 2.780400e+03],
       [2.321000e+02, 8.600000e+00, 8.700000e+00, 1.996060e+03,
        2.019270e+03, 7.482000e+01]])

In [0]:
X_inter.shape

(200, 6)

In [0]:
y = np.array(adv['sales'])
model3 = LinearRegression().fit(X = X_inter, y=y)
model3.score(X_inter,y)

0.9686311066255571

###Statistical Approach  
OLS Regression results  
look at R2, Adjusted R2  
AIC, BIC 越小越好  信息准则 类似于R2  
std error: coefficient 的std dev ,越大越不稳定  
p value = 0.001 假设coefficient对模型没有帮助，假设这个假设的假设是错的，所以发生这个假设的概率是0.001， 所以 假设coefficient对模型没有帮助 是错的，所以coefficient对模型有帮助  
assume it's not true, then the probability of this thing happen is 0.001


In [0]:
cred = pd.read_csv('/content/drive/My Drive/DS_Feb_21/data/credit.csv')

In [0]:
cred.head()

Unnamed: 0   Income  Limit  Rating  ...  Student  Married  Ethnicity Balance
0           1   14.891   3606     283  ...       No      Yes  Caucasian     333
1           2  106.025   6645     483  ...      Yes      Yes      Asian     903
2           3  104.593   7075     514  ...       No       No      Asian     580
3           4  148.924   9504     681  ...       No       No      Asian     964
4           5   55.882   4897     357  ...       No      Yes  Caucasian     331

[5 rows x 12 columns]

In [0]:
X = np.array(cred[['Income','Cards','Education','Limit','Rating','Age']])

y = np.array(cred['Balance'])
interaction = PolynomialFeatures(degree = 5, include_bias = False, interaction_only = False)
X_inter = interaction.fit_transform(X) 


0.9572062846390655

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
X_tain, X_test,y_train, y_test = train_test_split(X_inter,y,test_size = 0.3, random_state = 123)

model3 = LinearRegression().fit(X=X_inter,y=y)
mean_squared_error(y,model3.predict(X_inter)) #越靠近0，bias越小


9023.045459607074

In [0]:
X_inter.shape

(400, 461)

In [0]:
X_tain.shape

(280, 461)

In [0]:

model3 = LinearRegression().fit(X=X_tain, y=y_train)
mean_squared_error(y_test,model3.predict(X_test)) #实际看这个的结果

43964582.820515424

In [0]:
df = pd.read_csv('/content/drive/My Drive/DS_Feb_21/data/mpg.csv')
X = np.array(df['Weight']).reshape(-1,1)
interaction = PolynomialFeatures(degree = 2, include_bias = False)
X_inter = interaction.fit_transform(X)
model = LinearRegression().fit(X=X_inter,y=y)
model.score(X_inter,y)

#什么是overfitting， bias-variance trade-off low biased low variance 

ValueError: ignored

In [0]:
from sklearn.model_selection import train_test_split
X_tain, X_test,y_train, y_test = train_test_split(X_inter,y)



---



---



##Regularization   
avoid overfitting  
ridge regression - 要把数据都transform到一个unit（rescaling）  



In [0]:
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error

In [0]:
X = np.array(cred[['Rating','Limit','Income','Age','Education','Cards']])
y = np.array(cred['Balance'])
X_inter = PolynomialFeatures(degree = 2, include_bias = False).fit_transform(X)
model_slm = LinearRegression().fit(X=X_inter,y=y)
mean_squared_error(y, model_slm.predict(X_inter))

19900.75983764694

In [0]:
model_ridge = Ridge().fit(X=X_inter,y=y)
mean_squared_error(y,model_ridge.predict(X_inter))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=2.96186e-17): result may not be accurate.
  overwrite_a=True).T


19901.232681969475

In [0]:
model_lasso = Lasso(alpha = 100).fit(X=X_inter,y=y)
mean_squared_error(y,model_lasso.predict(X_inter))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4161841.3823197624, tolerance: 8433.991191
  positive)


20620.21584952593

In [0]:
model_lasso.coef_

array([ 0.00000000e+00,  5.84737702e-02, -0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  2.25718803e-03,  3.80887181e-05,
       -2.15189576e-02, -3.67106860e-03,  1.52292153e-02,  7.62385586e-02,
        2.20722457e-05, -1.59720610e-03, -1.63200421e-04,  3.15474692e-04,
       -2.28411326e-03,  6.99499242e-02,  2.77086743e-02, -3.31131586e-02,
       -7.18737995e-02, -1.78037364e-02,  1.36475897e-01, -3.56451352e-02,
       -3.87069722e-01, -0.00000000e+00,  0.00000000e+00])

In [0]:
model_ridge.coef_

array([ 2.44547094e+00, -7.18976534e-02, -2.49687094e+00,  7.79448191e+00,
        4.97125106e+00,  4.32566641e+01,  3.94433099e-02, -5.81453916e-03,
        3.12096205e-02, -6.65167320e-02,  1.56508795e-01, -5.07887881e-01,
        2.46299660e-04, -4.99100229e-03,  3.80573533e-03, -8.91818141e-03,
        4.11647280e-02,  6.39444402e-02,  4.69756856e-02, -2.41668260e-02,
       -3.24461018e-01, -5.91333268e-02,  1.17748797e-01, -1.13229693e-01,
       -4.23380777e-01, -3.30303281e+00,  2.58879882e+00])